[package]
name = "openssh-keys"
version = "0.1.0"
authors = ["Stephen Demos <stephen@demos.zone>"]
description = "read and write OpenSSH public keys"
documentation = "github.com/sdemos/ssh-keys"
homepage = "github.com/sdemos/ssh-keys"
repository = "github.com/sdemos/ssh-keys"
readme = "README.md"
keywords = ["ssh", "ssh-keys", "keys", "rsa"]
license = "MIT OR Apache-2.0"
exclude = ["fixtures/*"]

[dependencies]
error-chain = "0.10"
base64 = "0.6"
byteorder = "1.1"
rust-crypto = "0.2"
